version: '3.9'
services:
  mysqldevelopment:
    image: mysql:5.7.38
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: testapp
    ports:
      - "3308:3306"
    volumes:
        - "vol1:/var/lib/mysql"
        - "./tmp:/tmp"
        - "./yedek.sql:/docker-entrypoint-initdb.d/01_yedek.sql"
  fastapi:
      restart: always
      build: 
        context: ./
        dockerfile: Dockerfile
      volumes:
        - "./app:/app"
      ports:
        - 8000:8000
      depends_on:
        -  mysqldevelopment

volumes:
  vol1:

  